name: OPEN
on:
  push:
    branches:
    - develop
jobs:
  open:
    name: Generate text using Chat GPT API
    uses: ./.github/workflows/gpt.yaml
    with:
      api_key: ${{ secrets.CHAT_GPT }}
      engine: "davinci"
      prompt: "Hello, Chat GPT! Can you generate some text for me?"
