name: Generate text using OpenAI API

on:
  push:
    branches:
      - develop

jobs:
  generate-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'develop'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install http-requests
      
      - name: Generate text using OpenAI API
        run: |
          git checkout develop
          pwd

          ls -lrt

          python script.py
          
        env:
          OPENAI_API_KEY: ${{ secrets.CHAT_GPT }}
