name: Generate text using OpenAI API

on:
  push:
    branches:
      - develop

jobs:
  generate-text:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install http-requests
      
      - name: Generate text using OpenAI API
        run: |
          export DISPLAY=:0
          
          import os
          import json
          import http_requests

          api_key = os.environ['CHAT_GPT']
          url = 'https://api.openai.com/v1/engines/davinci-codex/completions'

          headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {api_key}'
          }

          data = {
            'prompt': 'Hello, Chat GPT! Can you generate some text for me?',
            'max_tokens': 100,
            'temperature': 0.5,
            'n': 1,
            'stop': '.'
          }

          response = http_requests.post(url, headers=headers, data=json.dumps(data))
          response_json = response.json()

          print(response_json['choices'][0]['text'])
          
        env:
          OPENAI_API_KEY: ${{ secrets.CHAT_GPT }}
